# Generated by Django 3.2.7 on 2021-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='0', upload_to='blogs'),
            preserve_default=False,
        ),
    ]
